language: python

python:
    - "3.4"

sudo: false
env:
    global:
        - CXX=g++-4.8
        - secure: ajoP9pA/FYH+1sFwGKHlQ8PoGqRIjdmqEnwo44AA5j6c1NMsgiToA420lPm8Lp0cko5YK3ppBlGlvbRWu5JXVxl0vMtZTLf3FM2w99viddrRCkh4sMef2DzkXXYOW4Tnew/8pmaOtTn3UtNG/feJHkBzHLEDUuN0TA07Y6UaWHc=

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - xvfb
    - build-essential
    - libudev-dev
    - clang-3.3
    - fakeroot
    - git
    - libgnome-keyring-dev
    - g++-4.8

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - cp $TRAVIS_BUILD_DIR/client/config.sample.js $TRAVIS_BUILD_DIR/client/config.js
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 4.5.0
    - npm install -g grunt-cli
    - export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
    - ./scripts/get-chrome-url | wget -N --no-verbose -i - && unzip chrome-linux.zip &&
      export CHROME_BIN=`pwd`/chrome-linux/chrome && $CHROME_BIN --version ;

install:
    - cd $TRAVIS_BUILD_DIR/client && npm i
    - ./node_modules/.bin/webdriver-manager update
    - cd $TRAVIS_BUILD_DIR/server && pip install -r requirements.txt

before_script:
    - cd $TRAVIS_BUILD_DIR/server
    - python3 manage.py app:initialize_data;
    - python3 manage.py users:create -u admin -p admin -e 'admin@example.com' --admin ;
    - python3 manage.py register_local_themes ;

script:
    - cd $TRAVIS_BUILD_DIR/client
    - grunt build ;
      cd dist ;
      while [ ! -f index.html ]; do sleep .5; done ;
        (nohup python -m http.server 9000 & );
      cd .. ;
    - cd $TRAVIS_BUILD_DIR/server
    - (nohup honcho -f ../docker/Procfile-dev start &) ;
    - sleep 10;
    - cd $TRAVIS_BUILD_DIR/client
    - ./node_modules/.bin/protractor protractor-conf.js
